name: count_number
description: Animates the counting process of a value based on a spring simulation. Starts an internal periodic timer that checks the state of the simulation.
version: 0.3.7
homepage: https://github.com/jibbex/count_number
repository: https://github.com/jibbex/count_number.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

